//------------------------------------------------------------------------------
//Client proxy script generated for Epicor Web Access services
//Date:    6/10/2013 10:35 PM
//Web Service version:  2.5.608.0
//This source code was auto-generated by Epicor EWA-ClientProxyGen tool, Version 2.0.11.0.
//*** Copyright  Epicor Software, Inc. ***
//------------------------------------------------------------------------------

function lib_LogOnService() {}

lib_LogOnService.prototype.LogIn=function(userID,password)
{

	var results = doVantageSoapCall('lib_LogOnService','LogIn(1)',['userID','password'],[],[userID,password]);
	
    if (results != undefined && results != null)
	{


    }
}

